# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

cache: packages

dist: bionic

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

jobs:
  exclude:
  - os: osx
    r: devel

before_install:
  - rm .Rprofile
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt install libgsl-dev; fi

addons:
  homebrew:
    packages:
      - gsl

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - gavin@gavincooper.net
    on_success: change
    on_failure: always
